---
kind: pipeline
type: docker
name: default

steps:
- name: APIsec scan trigger
  image: apisec/drone-scan:latest  
  environment:
     scanner: Super_1
     email: true
     hostUrl: https://developer.apisec.ai
     projectName: netbankingtet123
     profile: Master
     report: RUN_SUMMARY
     fail-on-high-vulns: true
     password:
       from_secret: apisec_password
     username:
       from_secret: apisec_username










































#---
#kind: pipeline
#type: docker
#name: default

#steps:
#- name: APIsec scan trigger
  #image: ubuntu
#  image: apisec/drone-scan:latest
#  commands:
#  - apt update
#  - apt install -y curl jq wget
#  - wget https://raw.githubusercontent.com/apisec-inc/apisec-scripts/master/apisec_job_invoke_script.sh?token=AVOLEQ4FVVPJJ3DPAME4JELBS56SI -O apisec_job_invoke_script.sh;bash apisec_job_invoke_script.sh --host https://developer.apisec.ai --username $USERNAME  --password $PASSWORD --project "nerwersdfprject" --profile Master --scanner Super_1 --emailReport true --reportType RUN_SUMMARY
#  - wget https://raw.githubusercontent.com/apisec-inc/apisec-scripts/master/apisec_job_invoke_script.sh?token=AVOLEQ4FVVPJJ3DPAME4JELBS56SI -O apisec_job_invoke_script.sh;bash apisec_job_invoke_script.sh --host https://developer.apisec.ai --username $USERNAME  --password $PASSWORD --project "nerwersdfprject" --profile Master --scanner $SCANNER --emailReport $EMAIL --reportType RUN_SUMMARY
#  - pwd
#  - ls -la
#  - echo "Script execition is finished"
  
#  environment:
#     scanner: Super_1
#     email: true
#     hostUrl: https://developer.apisec.ai
#     projectName: nerwersdfprject
#     profile: Master
#     report: RUN_SUMMARY
#     password:
#       from_secret: password
#     username:
#       from_secret: username
      
#  settings:
#    scanner: Super_1
##    email: true
#    hostUrl: https://developer.apisec.ai
#    projectName: nerwersdfprject
#    profile: Master
#    report: RUN_SUMMARY
#    password:
#      from_secret: password
#    username:
#      from_secret: username

  #environment:
  #  SCANNER: Super_1
  #  EMAIL: true
  #  PASSWORD:
  #    from_secret: password
  #  USERNAME:
  #    from_secret: username
      
